relativeURLs = true
title = "Shreya Chandra"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Agricultural and Resource Economics PhD Candidate"
    logo = "sc.jpg"
